Build binary-only packages, arch:all on amd64

diff --git a/slave/scripts/build-and-push-package b/slave/scripts/build-and-push-package
--- a/slave/scripts/build-and-push-package
+++ b/slave/scripts/build-and-push-package
@@ -212,13 +212,19 @@ cowbuilder_init() {
 
 identify_build_type() {
   # defaults
-  DEBBUILDOPTS="-sa"
+  DEBBUILDOPTS="-B" # -B -> build binary packages for current architecture only
   SKIP_ARCH_BUILD=false
 
   if [ "${architecture:-}" = "all" ] ; then
     echo "*** \$architecture is set to 'all', skipping further identify_build_type checks. ***"
-    echo "*** Consider setting \$architecture to amd64, i386,... instead. ***"
-    return 0
+    echo "*** ERROR: \$architecture has no valid value (all), consider setting it to amd64, i386,... instead. ***"
+    exit 2
+  fi
+
+  if [ "${architecture:-}" = "amd64" ] ; then
+    echo "*** Detected amd64 architecture/machine, building arch:all packages. ***"
+    # -b -> build only binary packages (arch:any, arch:all)
+    DEBBUILDOPTS="-b"
   fi
 
   if [ -z "${MAIN_ARCHITECTURE:-}" ] ; then
@@ -229,8 +235,6 @@ identify_build_type() {
     else
       echo "*** MAIN_ARCHITECTURE is unset. ***"
       echo "*** Host architecture [$(dpkg-architecture -qDEB_HOST_ARCH)] does not match \$architecture [${architecture:-}] ... ***"
-      echo "*** ... setting binary only build and continuing with identify_build_type ***"
-      DEBBUILDOPTS="-B"
     fi
   else
     if [ "${MAIN_ARCHITECTURE:-}" = "${architecture:-}" ] ;then
@@ -238,8 +242,7 @@ identify_build_type() {
       echo "*** MAIN_ARCHITECTURE matches \$architecture [${architecture:-}], using default ${DEBBUILDOPTS:-} buildoption ***"
       return 0
     else
-      echo "*** MAIN_ARCHITECTURE [${MAIN_ARCHITECTURE:-}] does not match \$architecture [${architecture:-}], setting binary only build and continuing with identify_build_type ***"
-      DEBBUILDOPTS="-B"
+      echo "*** MAIN_ARCHITECTURE [${MAIN_ARCHITECTURE:-}] does not match \$architecture [${architecture:-}], continuing with identify_build_type ***"
     fi
   fi
 
@@ -254,9 +257,7 @@ identify_build_type() {
 
       if grep -q '^Architecture: all' "$control_file" ; then
         if grep -q '^Architecture: any' "$control_file" ; then
-          echo "*** Package provides arch 'all' + 'any', enabling -B buildoption for this architecture. ***"
-          # -B -> binary-only build, limited to architecture dependent packages
-          DEBBUILDOPTS="-B"
+          echo "*** Package provides arch 'all' + 'any' (doing nothing at time). ***"
           break
         else
           # only "Architecture: all", so no arch specific packages since
